alias vk='chromium https://vk.com && clear'
alias y='chromium https://www.youtube.com && clear &'
alias anime='chromium https://animego.org && clear'
alias rasp='chromium "https://lk.ks.psuti.ru/?mn=2&obj=131" && clear'
alias kino='chromium https://kinoplay2.site/ && clear'
alias gpt='chromium https://chat.openai.com && clear'
alias you='chromium https://youcom && clear'
alias per='chromium https://www.perplexity.ai/ && clear'
alias f='chromium http://127.0.0.1:8000/docs && clear'
alias leet='chromium https://leetcode.com/problems/ && clear'
alias deepl='chromium https://www.deepl.com && clear'
alias mail='chromium https://e.mail.ru/inbox/ && clear'
alias ymail='chromium https://mail.yandex.ru/ && clear'
alias pmail='chromium https://mail.proton.me/u/0/inbox && clear'
alias temp='chromium https://temp-mail.org/ru/ && clear'
alias gh='chromium https://github.com/wisderfin && clear'
